
title: Luca Di Pierno's Website
description: Robotics, Autonomy & Space Systems
author: Luca Di Pierno
theme: minima
markdown: kramdown
highlighter: rouge
timezone: Etc/UTC

header_pages:
  - _pages/blog.md
  - _pages/projects.md
  - _pages/publications.md
  - _pages/about.md

# Add this line
sass:
  sass_dir: _sass
  style: compressed

# Enable the stylesheet
include:
  - _pages
  - assets/css


# Needed for GitHub Pages
url: "https://lucadipierno.github.io"
baseurl: ""


# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
